### ISSUE TITLE
Utiliser Git LFS pour les datasets

### ISSUE THREAD

**Issue by antoinetavant** [GreenForecast-Squad/energetic-stress-production#5]
Même si les fichiers CSV ne sont pas très gros, ça peut être une bonne pratique que d'utiliser git FLS pour ces fichiers:
https://docs.github.com/fr/repositories/working-with-files/managing-large-files/about-large-files-on-github

**Comment by BastienGauthier** [comment]
Franchement, tant que tu peux t'en passer, je te conseille de ne pas aller dans l'enfer des LFS !

**Comment by antoinetavant** [comment]
J'ai vu ça ! :D
